[package]
name = "cbrs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tungstenite = { version = "0.18.0", features = ["rustls-tls-native-roots"] }
url = "2.3.1"
